<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Imgs\cityBackground.png" />
    <None Remove="Imgs\clouds.png" />
    <None Remove="Imgs\clouds2.png" />
    <None Remove="Imgs\flappyBird.png" />
    <None Remove="Imgs\flappyboy.png" />
    <None Remove="Imgs\pipeBottom.png" />
    <None Remove="Imgs\pipeTop.png" />
    <None Remove="Imgs\radarBottom.png" />
    <None Remove="Imgs\radarTop.png" />
    <None Remove="Sounds\menumusic.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sounds\menumusic.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Imgs\cityBackground.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\clouds2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\flappyBird.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\flappyboy.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\pipeBottom.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\pipeTop.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\radarBottom.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imgs\radarTop.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
